[build]
  command = "npm run build"
  publish = "build"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  REACT_APP_API_URL = "https://your-backend-url.com"